### PR TITLE
forward port support for dns-json format to use last dns charm.

### PR DESCRIPTION
**Pull request by thomnico**

### CODE REVIEW

**Comment by mirw** [comment]
Ah, is this the correctly-merged version of https://github.com/Metaswitch/clearwater-juju/pull/30?  If so, shall we close that and I'll merge this?

**Comment by thomnico** [comment]
Hello Mirw it is a tested /working version for trusty without messing up with git access for the chef recipes

**Comment by thomnico** [comment]
I removed the "nogit" experiment .. this is the dns interaction which is necessary with the newer dns charm

**Comment by mirw** [comment]
@thomnico, thanks!

**Pull request merged**
