### PR TITLE
programmable-multiple relation to use the new DNS charm

### PR DESCRIPTION
**Pull request by thomnico**
Modify all programmable-multiple relation to use the new DNS charm using JSon.

### CODE REVIEW

**Comment by mirw** [comment]
@rkd-msw, please can you review?  It looks good to me.

**Comment by thomnico** [comment]
Feel free to test using instruction here : https://github.com/thomnico/juju-nfv-clearwater-restcomm

**Comment by thomnico** [comment]
Hello gents,

I did some more updates while working on the dns charm

**Comment by rkday-pro** [comment]
Thanks, Nicolas - but I believe we;re still waiting for you to provide a contributor's agreement before we can look at this or merge it.

**Comment by rkday-pro** [comment]
@thomnico , I've implemented an alternative approach to this in https://github.com/Metaswitch/clearwater-juju/pull/28 - if that works for you, should we just close this?

**Comment by thomnico** [comment]
Looks good (better) to me .. simply need to test it then

**Comment by thomnico** [comment]
Replaced by #28 which is much nicer

**Pull request closed without merging**
